environment: development
chdir: /home/lee/web/happygastropod
address: 127.0.0.1
user: root
group: root
port: 4567
pid: /home/lee/web/happygastropod/PID/thin.pid
rackup: /home/lee/web/happygastropod/server.ru
log: ./thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: false